# Generated by Django 4.1.2 on 2023-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county_revenue', '0002_remove_defaulter_address_remove_defaulter_amount_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaExpressResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_a', models.CharField(max_length=12)),
                ('transaction_time', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
