# Generated by Django 4.1.2 on 2023-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county_revenue', '0003_mpesaexpressresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.CharField(max_length=255)),
                ('customer_message', models.CharField(max_length=255)),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('response_json', models.JSONField()),
            ],
        ),
    ]
